<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 - Laboratorio N°02

## Objetivos de la clase

* Reforzar los conceptos básicos de numpy.

## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:


    * sma(2): [mean(1,2),mean(2,3),mean(3,4)] = [1.5, 2.5, 3.5, 4.5]
    * sma(3): [mean(1,2,3),mean(2,3,4),mean(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [192]:
import numpy as np

In [196]:
def sma(a, n): #funcion que calcula la media movil
    sma = np.zeros((1, len(a)- (n-1)))  # creo arreglo con la cantidad de columnas necesarias segun la ventana
    for i in range(0, sma.shape[1]): 
        sma[0, i] = ((1/n) * np.sum(a[i: i+n]))  #calculo el promedio con los datos de la ventana
    return sma
 
#Me da un error con las dimensiones ya que yo retorno un arreglo de dimension (1,4) y se pide verificar con uno de 
#dimension (4,)


SyntaxError: invalid syntax (<ipython-input-196-9af6f0d504b6>, line 7)

In [184]:
# ejemplo 01
a = [1,2,3,4,5]

np.testing.assert_array_equal(
    sma(a, n=2),
    np.array([1.5, 2.5, 3.5, 4.5])
)

AssertionError: 
Arrays are not equal

(shapes (1, 4), (4,) mismatch)
 x: array([[1.5, 2.5, 3.5, 4.5]])
 y: array([1.5, 2.5, 3.5, 4.5])

In [207]:
# ejemplo 02
a = [5,3,8,10,2,1,5,1,0,2]

np.testing.assert_array_equal(
    sma(a, n=2),
    np.array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])
)



AssertionError: 
Arrays are not equal

(shapes (1, 9), (9,) mismatch)
 x: array([[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]])
 y: array([4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ])

<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [188]:
def strides(a, n, p):
    filas = 0
    j= 0
    while j != len(a)-p: #verifico hasta llegar a la ultima fila que se creará
        j += (n-p)
        filas+=1 #contador de cantidad de filas
    j=0
    stride_1 = np.zeros((filas, n))
    for i in range(0, filas):
        stride_1[i] = a[j: j+n]
        j+=(n-p)
    return stride_1

𝑎 = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]    
print(strides(a,4,2))     

[[ 1.  2.  3.  4.]
 [ 3.  4.  5.  6.]
 [ 5.  6.  7.  8.]
 [ 7.  8.  9. 10.]]


In [ ]:
def strides(a, n, p):
    filas = 0
    for i*n in range(0, len(a)):
        
        

In [63]:
# ejemplo 01
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
n=4
p=2

np.testing.assert_array_equal(
    strides(a,n,p),
    np.array([
       [ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]])
)

<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

In [193]:
def es_cuadrada(A):  #funcion para verificar que la matriz es cuadrada
    return A.shape[0] == A.shape[1]  #verifico que las filas sean iguales a las columnas

def son_consecutivos(A): #función para ver si las entradas de una matriz son numeros consecutivos
    Flag = False
    list_comp = [i for i in range(1, (A.shape[0])**2 + 1)] #defino lista con la cantidad de numeros como filas al cuadrado se 
                                                            #tengan
    list_A = []
    for i in range(0, A.shape[0]):
        for j in range(0, A.shape[1]):
            list_A.append(A[i][j])  #agrego las entradas de la matriz a una lista
    list_A.sort()   #ordeno la lista con las entradas de la matriz
    if list_A == list_comp:  #verifico si son iguales ambas listas
        Flag = True
    return Flag

def es_cuadrado_magico(A):  #funcion para ver si es cuadrado magico
    Flag = True
    if es_cuadrada(A) and son_consecutivos(A):  #verifico que se cumplan las condiciones necesarias
        M_n  = A.shape[0] * (A.shape[0]**2 + 1) / 2 #como los numeros son consecutivos defino la suma del cuadrado magico
        if np.sum(np.diag(A)) != M_n:  #verifico si falla la suma de la diagonal
            Flag = False
            return Flag
        for i in range(0, A.shape[0]):
            if np.sum(A[i, 0: A.shape[1]]) != M_n:  #verifico si falla la suma de las filas
                Flag = False
                return Flag
            if np.sum(A[0: A.shape[1], i]) != M_n:  #verifico si falla la suma de las columnas
                Flag = False
                return Flag
        return Flag
    if not (es_cuadrada(A) and son_consecutivos):
        return 'La matriz ingresada no es cuadrada ni posee entradas consecutivas'
    if not(es_cuadrada(A)):
        return 'La matriz ingresada no es cuadrada'
    if not(son_consecutivos(A)):
        return 'La matriz ingresada no posee entradas consecutivas'


In [194]:
# ejemplo 01
A = np.array([[4,9,2],[3,5,7],[8,1,6]])
assert es_cuadrado_magico(A) == True, "ejemplo 01 incorrecto"



In [195]:
# ejemplo 02
B = np.array([[4,2,9],[3,5,7],[8,1,6]])
assert es_cuadrado_magico(B) == False, "ejemplo 02 incorrecto"