<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281- Buenas prácticas

## Objetivos 

* Aprender buenas prácticas en python.


## Contenidos

* [Estilo de codificación](#c1)
* [Zen de python](#c2)

<a id='c1'></a>
## I.- Estilo de codificación

<img src="images/pep8.png" width="240" height="240" align="center"/>

Además de una correcta y ordenada estructura general que deben tener los programa, es conveniente mantener ciertas buenas prácticas de codificación y el estilo de codificación recomendado. Estas normas no son obligatorias, como lo es la propia sintaxis del lenguaje, pero conviene [seguir las recomendaciones](https://legacy.python.org/dev/peps/pep-0008/) de los desarrolladores de Python para facilitar la lectura del programa y ayudar a encontrar posibles errores.


### Variables
Cuando sea posible, define variables con nombres que tengan algún sentido o que puedas identificar fácilmente, no importa que sean más largas. Por ejemplo, en un programa podríamos escribir:

In [1]:
a = 10.  # altura
b = 3.5  # base
print("El volumen es %.1f" % (a*b))

El volumen es 35.0


pero, ¿qué significan `a` y  `b`? lo sabemos por el comentario (bien hecho), pero si más adelante nos encontramos con esas variables, tendremos que recordar cual es cual. Es mejor usar nombres con significado:

In [2]:
altura = 10.
base = 3.5
print("El volumen es %.1f" % (altura*base))

El volumen es 35.0


De hecho podemos usar el nombre para dar más información sobre la variable:



In [3]:
velocidad_metros_segundo = 12.5
angulo_radianes = 1.3

### Lineas de códigos

Las líneas de codigo no deben ser muy largas, como mucho 72 caracteres. Si se tiene una línea larga, se puede cortar con una barra invertida (`\`) y continuar en la siguiente línea:

In [4]:
print("Esta es una frase muy larga, se puede cortar con una \
       y seguir en la línea inferior.")

Esta es una frase muy larga, se puede cortar con una        y seguir en la línea inferior.


### Comentarios

Los comentarios son muy importantes al escribir un programa. Describen lo que está sucediendo dentro de un programa, para que una persona que mira el código fuente no tenga dificultades para descifrarlo.


In [5]:
# esto es un comentario
print('Hola')

Hola


También podemos tener comentarios multilíneas:

In [6]:
# Este es un comentario largo
# y se extiende
# a varias líneas

### Identación

a)  Dentro de paréntesis, corchetes o llaves, no dejar espacios inmediatamente dentro de ellos:

In [1]:
# no:  
lista_01 = [1, 2, 3,4, 5, 6,7, 8, 9,]

In [2]:
# si 
lista_01 = [
    1, 2, 3,
    4, 5, 6,
    7, 8, 9, 
]

b) Aunque en Python se pueden hacer varias declaraciones en una línea, se recomienda hacer sólo una en cada línea:



In [9]:
# no
a = 10; b = 20

In [10]:
# si
a = 10
b = 20    

c) Cuando se trabaja con lista, conjuntos y/o tuplas se recomienda poner en cada línea sus argumentos.


In [11]:
# no
lista = [(1, 'hola'),(2, 'mundo'),]

In [12]:
# si
lista = [
    (1, 'hola'),
    (2, 'mundo'),
]

d) Lo anterior se puede extender para funciones con muchos argumentos

In [13]:
# no
def funcion_01(x1,x2,x3,x4):
    print(x1,x2,x3,x4)
    
def funcion_02(
    x1,x2,x3,x4):
    print(x1,x2,x3,x4)

In [14]:
# si
def funcion_01(x1,x2,
               x3,x4):
    
    print(x1,x2,x3,x4)
    
def funcion_02(
        x1,x2,
        x3,x4):
    
    print(x1,x2,x3,x4)

### Manipulación de listas

Aunque combinar iterables con elementos de control de flujo para manipular listas es muy sencillo con Python, hay métodos específicos más eficientes para hacer lo mismo. Pensemos el fitrado de datos de una lista:

In [1]:
# Seleccionar los números positivos
numeros = [-3, 2, 1, -8, -2, 7]
positivos = []
for i in numeros:
    if i > 4:
        positivos.append(i)


Aunque técnicamente es correcto, es más eficiente hacer algo como esto usando las posibilidades de Python:



In [2]:
numeros = [-3, 2, 1, -8, -2, 7]
positivos = [i for i in numeros if i > 4]

# o también:
positivos = filter(lambda x: x > 4, numeros)

Igualmente, aunque se puede hacer esto:



In [17]:
numeros = [-3, 2, 1, -8, -2, 7]
for i in range(len(numeros)):
    numeros[i] += 3

Es mejor hacer esto otro:

In [18]:
numeros = [-3, 2, 1, -8, -2, 7]
numeros = [i + 3 for i in numeros]

o también:

In [19]:
numeros = map(lambda i: i + 3, numeros)

### Parámetros de funciones

Con Python 3 se puede especificar el tipo de parámetro y el tipo de retorno de una función. Esto es útil porque:
* Se definen explicitamente el formato del input y del output
* Si se ingresa un formato que no es el especificado, nos devolverá un `TypeError`

In [13]:
def pick(
    l: list,
    index: int) -> int:
    return l[index]

In [14]:
# ejemplo 
l = [1,2,3,4,5]
index= 1 # int 
type(pick(l,index))

int

In [15]:
# error tipo de argumento
l = [1,2,3,4,5]
index= 1.0 # float
pick(l,index)

TypeError: list indices must be integers or slices, not float

### Documentación de código

Casi tan importante como la escritura de código, es su correcta documentación, una parte fundamental de cualquier programa que a menudo se infravalora o simplemente se ignora. Aparte de los comentarios entre el código explicando cómo funciona, el elemento básico de documentación de Python es el Docstring o cadena de documentación, que ya hemos visto. Simplemente es una cadena de texto con triple comillas que se coloca justo después de la definición de función o clase que sirve de documentación a ese elemento.

In [23]:
def potencia(x, y):
    """
    Calcula la potencia arbitraria de un numero
    """
    return x**y

In [24]:
# Acceso a la documentación
potencia.__doc__

'\n    Calcula la potencia arbitraria de un numero\n    '

In [25]:
# Acceso a la documentación
help(potencia)

Help on function potencia in module __main__:

potencia(x, y)
    Calcula la potencia arbitraria de un numero



Lo correcto es detallar lo mejor posible en el *Docstring* qué hace y cómo se usa la función o clase y los parámetros que necesita. Se recomienda usar el estilo de documentación del software de documentación [sphinx](https://www.sphinx-doc.org/en/master/), que emplea [reStructuredText](https://docutils.sourceforge.io/rst.html) como lenguaje de marcado.

Veamos un ejemplo de una función bien documentada:

In [26]:
def potencia(x, y):
    """
    power(x1, x2[, out])

    First array elements raised to powers from second array, element-wise.

    Raise each base in `x1` to the positionally-corresponding power in
    `x2`.  `x1` and `x2` must be broadcastable to the same shape. Note that an
    integer type raised to a negative integer power will raise a ValueError.

    Parameters
    ----------
    x1 : array_like
        The bases.
    x2 : array_like
        The exponents.

    Returns
    -------
    y : ndarray
        The bases in `x1` raised to the exponents in `x2`.

    See Also
    --------
    float_power : power function that promotes integers to float
    
    
    Examples
    --------
    Cube each element in a list.

    >>> x1 = range(6)
    >>> x1
    [0, 1, 2, 3, 4, 5]
    >>> np.power(x1, 3)
    array([  0,   1,   8,  27,  64, 125])

    Raise the bases to different exponents.

    >>> x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
    >>> np.power(x1, x2)
    array([  0.,   1.,   8.,  27.,  16.,   5.])

    The effect of broadcasting.

    >>> x2 = np.array([[1, 2, 3, 3, 2, 1], [1, 2, 3, 3, 2, 1]])
    >>> x2
    array([[1, 2, 3, 3, 2, 1],
           [1, 2, 3, 3, 2, 1]])
    >>> np.power(x1, x2)
    array([[ 0,  1,  8, 27, 16,  5],
           [ 0,  1,  8, 27, 16,  5]])
       
    """
    return x**y

In [27]:
# Acceso a la documentación
potencia.__doc__

'\n    power(x1, x2[, out])\n\n    First array elements raised to powers from second array, element-wise.\n\n    Raise each base in `x1` to the positionally-corresponding power in\n    `x2`.  `x1` and `x2` must be broadcastable to the same shape. Note that an\n    integer type raised to a negative integer power will raise a ValueError.\n\n    Parameters\n    ----------\n    x1 : array_like\n        The bases.\n    x2 : array_like\n        The exponents.\n\n    Returns\n    -------\n    y : ndarray\n        The bases in `x1` raised to the exponents in `x2`.\n\n    See Also\n    --------\n    float_power : power function that promotes integers to float\n    \n    \n    Examples\n    --------\n    Cube each element in a list.\n\n    >>> x1 = range(6)\n    >>> x1\n    [0, 1, 2, 3, 4, 5]\n    >>> np.power(x1, 3)\n    array([  0,   1,   8,  27,  64, 125])\n\n    Raise the bases to different exponents.\n\n    >>> x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]\n    >>> np.power(x1, x2)\n    array([  0., 

In [28]:
# Acceso a la documentación
help(potencia)

Help on function potencia in module __main__:

potencia(x, y)
    power(x1, x2[, out])
    
    First array elements raised to powers from second array, element-wise.
    
    Raise each base in `x1` to the positionally-corresponding power in
    `x2`.  `x1` and `x2` must be broadcastable to the same shape. Note that an
    integer type raised to a negative integer power will raise a ValueError.
    
    Parameters
    ----------
    x1 : array_like
        The bases.
    x2 : array_like
        The exponents.
    
    Returns
    -------
    y : ndarray
        The bases in `x1` raised to the exponents in `x2`.
    
    See Also
    --------
    float_power : power function that promotes integers to float
    
    
    Examples
    --------
    Cube each element in a list.
    
    >>> x1 = range(6)
    >>> x1
    [0, 1, 2, 3, 4, 5]
    >>> np.power(x1, 3)
    array([  0,   1,   8,  27,  64, 125])
    
    Raise the bases to different exponents.
    
    >>> x2 = [1.0, 2.0, 3.0, 3.0, 

### Tipos de Docstring
Existen varias formas de documentar tus funciones, las principales encontradas en la literatura son:
  * [Google docstrings](https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings):Google’s recommended form of documentation.
  * [reStructured Text](http://docutils.sourceforge.net/rst.html):Official Python documentation standard; Not beginner friendly but feature rich.
  * [NumPy/SciPy docstrings](https://numpydoc.readthedocs.io/en/latest/format.html):NumPy’s combination of reStructured and Google Docstrings.
  * [Epytext](http://epydoc.sourceforge.net/epytext.html)A Python adaptation of Epydoc; Great for Java developer."

<a id='c2'></a>
## II.- Zen de python

<img src="images/zen.jpg" width="480" height="240" align="center"/>

El **Zen** de Python te dará la guía para decidir sobre que hacer con tu código, no te dice como lo debes escribir, sino como debes pensar si estas programando en Python.

Principios importantes:

* **Explícito es mejor que implícito**: Que no se asuma nada, asegúrate que las cosas sean.
* **Simple es mejor que complejo**: Evita código complejo, código espagueti o que hace mas cosas para poder hacer una simple tarea.
* **Plano es mejor que anidado**: Si tu código tiene mas de 3 niveles de identación, deberías mover parte de ese código a una función.
* **Los errores nunca deberían pasar silenciosamente**: No uses un Try/Except sin definir que tipo de error vas a cachar, viene de la mano con Explicito es mejor que implícito.
* **Si la implementación es difícil de explicar, es mala idea**.


También, podemos ver el mensaje original del zen de python, ejecutando la siguiente linea de comando.

In [29]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


## Referencia

1. [clean-code-python](https://github.com/zedr/clean-code-python)
1. [Documenting Python Code: A Complete Guide](https://realpython.com/documenting-python-code/)
